#!/usr/bin/env bash
#This script displays 1 to 100, fizz for multiples of 3 and buzz for multiples of 5
i=1
while [ $i -le 100 ]
do
	if [ $(( i % 3 ))  == 0 ]
	then
		echo "fizz"
	elif [ $(( i % 5 )) == 0 ]
	then
		echo "buzz"
	else
		echo $i
	fi
	i=$(( i + 1))
done
